<?php if($this->getItems()->getSize()): ?>
<div class="box base-mini mini-related-items">
    <div class="head">
        <h4><?php echo $this->__('Related Products') ?></h4>
    </div>
    <div class="content">
        <p><strong><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this);return false;"><?php echo $this->__('select all') ?></a></strong></p>
        <ol>
        <?php foreach($this->getItems() as $_item): ?>
        <li<?php if($_item->isSuper() || !$_item->isSaleable()): ?> class="super-products"<?php endif; ?>>
            <div class="product-images">
            <?php if(!$_item->isSuper() && $_item->isSaleable()): ?>
                <span class="checkbox-container">
                    <input type="checkbox" class="related-checkbox left" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                </span>
            <?php else: ?>
                <span class="checkbox-container">&nbsp;</span>
            <?php endif; ?>
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="50" height="50" /></a>
            </div>
            <div class="product-details">
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <?php echo $this->helper('catalog/product')->getPriceHtml($_item, true) ?>
                    <?php if($_item->isSuper()): ?>
                        <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a><br/>
                    <?php else: ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                    <?php endif; ?>
            </div>
        </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>
