<table cellspacing="0" class="shopping-cart checkout-review" id="checkout-review-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <?php echo $this->getChildHtml('totals'); ?>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item)?>
    <?php endforeach ?>
    </tbody>
</table>
