<form id="co-billing-form" method="post" action="<?php echo$this->getSaveUrl();?>">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ($this->customerHasAddresses()): ?>
    <p><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></p>
    <ul><li><p class="select300inner"><?php echo $this->getAddressesHtmlRadio('billing') ?></p></li></ul>

<?php endif ?>
    <fieldset>

    <fieldset class="group-select" id="billing-new-address-form">
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
        <ul class="form-list">
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:firstname"><?php echo $this->__('First Name') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->htmlEscape($this->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" class="required-entry input-text" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:lastname"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo $this->htmlEscape($this->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" class="required-entry input-text" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:company"><?php echo $this->__('Company') ?></label>
                </div><div class="col-2">
                    <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                </div></div><div class="clear"></div>
            </li>
            <?php if(!$this->isCustomerLoggedIn()): ?>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="validate-email required-entry input-text" />
                </div></div><div class="clear"></div>
            </li>
            <?php endif ?>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:street1"><?php echo $this->__('Address') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][1]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="required-entry input-text" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    &nbsp;
                </div><div class="col-2">
                    <input type="text" title="<?php echo $this->__('Street Address 2') ?>" name="billing[street][2]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:city"><?php echo $this->__('City') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="required-entry input-text" id="billing:city" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:region"><?php echo $this->__('State/Province') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    <?php $_region = Zend_Json::decode($this->helper('directory')->getRegionJson());?>
                    <?php foreach( $_region['JP'] as $_region_id => $_regiondata ) : ?>
                        <option value="<?php echo $_region_id ?>"><?php echo $_regiondata['name']; ?></option>
                    <?php endforeach; ?>
                    </select>
                    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="validate-zip-international required-entry input-text" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:country_id"><?php echo $this->__('Country') ?> <span class="required">*</span></label>
                </div><div class="col-2 select190inner">
                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="billing:telephone" />
                </div></div><div class="clear"></div>
            </li>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                </div><div class="col-2">
                    <input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="billing:fax" />
                </div></div><div class="clear"></div>
            </li>
            <?php if(!$this->isCustomerLoggedIn()): ?>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                        <li>
                            <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())
                                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </li>
            <?php endif ?>

            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                        <li>
                            <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </li>
            <?php endif ?>

            <li id="register-customer-password">
                <div class="col2-alt-set"><div class="col-1">
                    <label for="billing:customer_password"><?php echo $this->__('Password') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="required-entry validate-password input-text" />
                </div></div><div class="clear"></div>
                <div class="col2-alt-set" style="margin-top:8px;"><div class="col-1">
                    <label for="billing:confirm_password"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label>
                </div><div class="col-2">
                    <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="required-entry validate-password input-text" />
                </div></div><div class="clear"></div>
            </li>
            <?php endif ?>
            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <li>
                <div class="col2-alt-set"><div class="col-1">
                    <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> />
                </div><div class="col-2">
                    <label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </div></div><div class="clear"></div>
            </li>
            <?php else:?>
            <input type="hidden" name="billing[save_in_address_book]" value="1" />
            <?php endif;?>
        </ul>
    </fieldset>
<div class="col2-alt-set button-set">
    <div class="col-1">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    </div>
    <div class="col-2">
        <div class="form-buttons">
            <span id="billing-buttons-container" >
                <span id="billing-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span><br />
                <input type="submit" class="form-button right" value="<?php echo $this->__('Continue') ?>" name="submit" />
            </span>
        </div>
    </div>
</div>
</form>
<div class="clear"></div>
