<div class="col2-set">
    <div class="col-1">
        <h4>&nbsp;<br /><?php echo $this->__('Login') ?></h4>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <p><strong><?php echo $this->__('Already registered?') ?></strong><br />
            <?php echo $this->__('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
                    <input type="text" class="input-text required-entry validate-email" id="email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                </li>
                <li>
                    <label for="password"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
                    <input type="password" class="input-text required-entry" id="password" name="login[password]" />
                </li>
            </ul>
            <p class="required a-right" style="padding-right:8px;"><?php echo $this->__('* Required Fields') ?></p>
            <p class="a-right" style="padding-right:8px;"><input type="submit" name="submit" class="form-button" value="<?php echo $this->__('Login') ?>" /></p>
            <p class="a-center" style="padding-top:5px;"><a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="left"><?php echo $this->__('Forgot your password?') ?></a></p>
        </form>
    </div>
    <div class="col-2">
    <form method="post" action="<?php echo $this->getPostActionUrl() ?>">
        <h4><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest<br />or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h4>

        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php else: ?>
            <strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?>
            <ul class="disc">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li style="marin:0;padding:0;">
                    <div class="col2-alt-set">
                        <div class="col-1">
                            <input type="radio" name="checkout_method" id="guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_GUEST): ?> checked="checked"<?php endif ?> />
                        </div>
                        <div class="col-2" style="padding-top:5px;">
                            <label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                        </div>
                    </div><div class="clear"></div>
                </li>
                <?php endif; ?>
                <li style="marin:0;padding:0;">
                    <div class="col2-alt-set">
                        <div class="col-1">
                            <input type="radio" name="checkout_method" id="register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> />
                        </div>
                        <div class="col-2" style="padding-top:5px;">
                            <label for="login:register"><?php echo $this->__('Register') ?></label>
                        </div>
                    </div><div class="clear"></div>
                </li>
            </ul>
            <div style="margin:10px 5px 0 5px;">
                <strong><?php echo $this->__('Register and save time!') ?></strong><br />
                <?php echo $this->__('Register with us for future convenience:') ?>
                <ul class="disc">
                    <li><?php echo $this->__('Fast and easy check out') ?></li>
                    <li><?php echo $this->__('Easy access to your order history and status') ?></li>
                </ul>
            </div>
            <?php else: ?>
                <input type="hidden" name="checkout_method" id="register" value="register" checked="checked" />
            <?php endif; ?>
            <div class="col2-alt-set button-set" style="padding-top:5px;">
                <div class="col-1">
                    <p class="required">&nbsp;</p>
                </div>
                <div class="col-2">
                    <div class="form-buttons">
                        <input type="submit" class="form-button" name="submit" value="<?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?>" />
                    </div>
                </div>
            </div><div class="clear"></div>
        </form>
    </div>
</div><div class="clear"></div>
