<form id="co-shipping-method-form" method="post" action="<?php echo $this->getSaveUrl(); ?>">
<div class="inner-box">
    <div class="default-box" style="padding:10px;" id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
</div>
<div id="onepage-checkout-shipping-method-additional-load">
<?php echo $this->getChildHtml('additional') ?>
</div>
<div class="col2-alt-set button-set" style="padding-top:0;">
    <div class="col-1" style="padding-top:8px;">
        <a href="#" class="left" onclick="checkout.back(); return false;"><span><?php echo $this->__('&laquo Back') ?></span></a>
    </div>
    <div class="col-2">
        <div class="form-buttons">
            <span id="shipping-method-buttons-container">
                <input type="submit" class="form-button right" value="<?php echo $this->__('Continue') ?>" name="submit" />
            </span>
        </div>
    </div>
</div>
</form>
<div class="clear"></div>
