<?php
/**
 * Ship to multiple address template
 *
 * @see Mage_Checkout_Block_Multishipping_Addresses
 */
?>
<div class="in-page">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
    <div class="page-head col2-set">
        <div class="col-1" style="width:60%;">
            <h3><?php echo $this->__('Ship to Multiple Addresses') ?></h3>
        </div>
        <div class="col-2 a-right" style="width:38%;">
        </div><div class="clear" />
    </div><br />
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <fieldset>
        <input type="hidden" name="continue" value="0" id="can_continue_flag"/>
        <input type="hidden" name="new_address" value="0" id="add_new_address_flag" />
            <tbody>
            <?php foreach ($this->getItems() as $_index => $_item): ?>
                <tr>
                    <td class="a-right v-top" style="padding-top:8px;"><strong><?php echo $this->__('Send to: ') ?></strong></td>
                    <td class="v-top select250inner" colspan="2"><?php echo $this->getAddressesHtmlSelect($_item, $_index) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <div class="col2-set" style="margin:10px 0;">
            <div class="col-1" style="padding:8px 0;"><a href="<?php echo $this->getBackUrl() ?>" class="left"><?php echo $this->__('&laquo; Back to Shopping Cart') ?></a></div>
        </div>
        <div class="a-center" style="margin:15px 0;">
            <button class="form-button" type="submit" onclick="$('can_continue_flag').value=1"><span><?php echo $this->__('Continue to Shipping Information') ?></span></button>
        </div>
        <div style="margin:20px 0;"></div>
    </fieldset>
    </form>
</div>
