<div class="in-page">
    <div class="page-head">
        <h3><?php echo $this->__('Select Shipping Method') ?></h3>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="shipping_method_form">
    <div class="multi-address-checkout-box">
    <?php $_addresses = $this->getAddresses(); ?>
    <?php foreach ($_addresses as $_index => $_address): ?>
    <div class="box">
        <table class="shopping-cart">
            <thead>
                <tr>
                    <th class="a-left">
                        <div class="col2-set">
                            <div class="col-1"><?php echo $this->__('Shipping to') ?></div>
                            <div class="col-2 a-right"><a href="<?php echo $this->getAddressEditUrl($_address) ?>"><?php echo $this->__('Change Shipping Address') ?></a></div>
                        </div><div class="clear"></div>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <address>
                            <?php echo $_address->format('html') ?>
                        </address>
                    </td>
                </tr>
            </tbody>
        </table><br />
        <div class="shipping-method-pointer">
            <div class="inner-head">
                <h5><?php echo $this->__('Shipping Method') ?></h5><div class="clear"></div>
            </div>
            <?php if (!($_shippingRateGroups = $this->getShippingRates($_address))): ?>
                <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
            <?php else: ?>
            <dl class="shipment-methods">
                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                    <dt><?php echo $this->getCarrierName($code) ?></dt>
                    <dd>
                        <ul>
                        <?php foreach ($_rates as $_rate): ?>
                            <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                    <strong><?php echo $_rate->getCarrierTitle() ?>: <?php echo $_rate->getErrorMessage() ?></strong>
                            <?php else: ?>
                                    <input name="shipping_method[<?php echo $_address->getId() ?>]" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod($_address)) echo ' checked="checked"' ?> />
                                    <label for="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?> - <strong><?php echo $_rate->getPrice() ?></strong></label>
                            <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
        </div>
        <div>
            <?php echo $this->helper('giftmessage/message')->getInline('multishipping_adress_checkbox', $_address); ?>
        </div>
        <div class="clear"></div>
        <?php echo $this->helper('giftmessage/message')->getInline('multishipping_adress', $_address); ?>
    </div>
    <?php endforeach; ?>
    </div>
    <div class="a-right">
        <button  class="form-button" type="submit"><span><?php echo $this->__('Continue to Billing Information') ?></span></button>
    </div><br />
    <div><a href="<?php echo $this->getBackUrl() ?>" class="left"><?php echo $this->__('&laquo; Back to Select Addresses') ?></a></div>
    </form>
</div><br /><br />
