<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>

<?php echo $this->getToolbarHtml() ?>
<?php // List mode ?>

<?php $_iterator = 0; ?>
<div class="listing-type-list catalog-listing">
<ul class="c-list">
<?php foreach ($_productCollection as $_product): ?>
    <li>
    <div class="col2-alt-set">
        <div class="col-1">
            <?php // Product Image ?>
            <div class="product-image">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(65, 65); ?>" width="65" height="65" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                </a>
            </div>
        </div>
        <div class="col-2">
            <?php // Product description ?>
            <div class="product-shop">
                <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h5>
                <div class="product-price"><?php echo $this->getPriceHtml($_product, true) ?></div>
            </div>
        </div><div class="clear"></div>
    </div>
</li>
<?php endforeach; ?>
</ul>
</div>

<?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
