<form method="post" action="<?php echo $this->getSaveUrl(); ?>">
<div class="payment-methods">
    <dl id="checkout-payment-method-load">
    <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
        <dt>
        <?php if( sizeof($this->getMethods()) > 1 ): ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" <?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> />
        <?php else: ?>
            <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
        <?php endif; ?>
            <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
        </dt>
        <dd>
            <?php echo $this->getChildHtml('payment.method.'.$_code) ?>
        </dd>
    <?php endforeach; ?>
    </dl>
<div class="col2-alt-set button-set" style="padding-top:0;">
    <div class="col-1" style="padding-top:8px;">
        <a href="#" class="left" onclick="checkout.back(); return false;"><span><?php echo $this->__('&laquo Back') ?></span></a>
    </div>
    <div class="col-2">
        <div class="form-buttons">
            <span id="shipping-method-buttons-container">
                <input type="submit" class="form-button right" value="<?php echo $this->__('Continue') ?>" name="submit" />
            </span>
        </div>
    </div>

</div>
</form>
