<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php if($_additional = $this->getAdditionalData()): ?>
<div class="collateral-box attribute-specs">
    <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
    <?php foreach ($_additional as $_data): ?>
    <tr>
        <td class="label"><?php echo $_data['label'] ?></td>
        <td class="data"><?php echo $_data['value'] ?></td>
    </tr>
    <?php endforeach; ?>
    </table>
</div>
<?php endif;?>
