<div class="header-top">
    <div class="col2-alt-set">
        <div class="col-1">
            <h1 id="logo"><a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        </div>
        <div class="col-2">
            <div class="user-links">
                <?php echo $this->getChildHtml('user_links') ?>
            </div>
        </div>
    </div>
</div>
<div class="shop-access">
    <?php echo $this->getChildHtml('topLinks') ?>
</div><div class="clear"></div>
